// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlcUQG16UygV8xuWlSRKjHKqovqoVLgzQ',
    appId: '1:750411735813:web:151ddacfc9dd3585b40d6c',
    messagingSenderId: '750411735813',
    projectId: 'fir-auth-4b2df',
    authDomain: 'fir-auth-4b2df.firebaseapp.com',
    storageBucket: 'fir-auth-4b2df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Lmm6NygCeZeAHJliiu7t6FzfzuJbs00',
    appId: '1:750411735813:android:5cede54ace5dd62db40d6c',
    messagingSenderId: '750411735813',
    projectId: 'fir-auth-4b2df',
    storageBucket: 'fir-auth-4b2df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9Z6dtfNo27-dNDHX6jKWPyv1-3Rs2J8',
    appId: '1:750411735813:ios:ea6f3a6682b422b6b40d6c',
    messagingSenderId: '750411735813',
    projectId: 'fir-auth-4b2df',
    storageBucket: 'fir-auth-4b2df.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj9Z6dtfNo27-dNDHX6jKWPyv1-3Rs2J8',
    appId: '1:750411735813:ios:ea6f3a6682b422b6b40d6c',
    messagingSenderId: '750411735813',
    projectId: 'fir-auth-4b2df',
    storageBucket: 'fir-auth-4b2df.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlcUQG16UygV8xuWlSRKjHKqovqoVLgzQ',
    appId: '1:750411735813:web:6a1f3ed1e1e15fc4b40d6c',
    messagingSenderId: '750411735813',
    projectId: 'fir-auth-4b2df',
    authDomain: 'fir-auth-4b2df.firebaseapp.com',
    storageBucket: 'fir-auth-4b2df.appspot.com',
  );

}